### ISSUE TITLE
Any chance of a new release with the ping / channel name fix?

### ISSUE THREAD

**Issue by ConfusedVorlon** [nerzh/Action-Cable-Swift#15]
I nearly gave up on this package as my pings were not getting through.
I eventually figured out the issue, went to check the source and found that it has been fixed - but not released...

thanks :)

**Comment by nerzh** [comment]
are you talking about the ping that the rails application sends ?

as far as I remember rails had some problem with this and the ping never came, if they fixed it and you are sure that the ping is coming from the backend, then I will try to solve this problem for the swift client

**Comment by ConfusedVorlon** [comment]
Hi - Ping is definitely coming from the backend on Rails 7.0.4

To be clear - this issue is fixed already on master after you accepted this pull request:
https://github.com/nerzh/Action-Cable-Swift/commit/6b85886cc01a30c2b6322019271181c120bfc4b0

It's just that you need to user master, rather than the latest release to get the fix.

**Comment by nerzh** [comment]
I forgot to make a release?! ) I did it, is it ok now?

**Comment by ConfusedVorlon** [comment]
thank you :)
