### ISSUE TITLE
WSS non Starscream class thread warning(s)

### ISSUE THREAD

**Issue by wambambizzle** [nerzh/Action-Cable-Swift#18]
Action Cable Swift- 0.4.0
Web socket kit - 2.14.0
Xcode - 15.0

I have a class setup like the `WSS` from the non Starscream example. The thread checker always catches at least 1, but sometimes two threading issues related to `WSS` init `MultiThreadedEventLoopGroup`.

```
final class WSS: ACWebSocketProtocol {

  var url: URL
  private var eventLoopGroup: EventLoopGroup
  @Atomic var ws: WebSocket?

  init(stringURL: String, coreCount: Int = System.coreCount) {
      url = URL(string: stringURL)!
      eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: coreCount)
  }
  ```

It then directly shows an issue with `loopUpAndRunningGroup.wait()` inside of `MultiThreadEvenLoopGroup` class, around line 125:
> Thread running at User-interactive quality-of-service class waiting on a lower QoS thread running at Default quality-of-service class. Investigate ways to avoid priority inversions

Haven't seen other issues related to it. Any help or guidance is appreciated.

**Comment by nerzh** [comment]
but the code continues to work? I also see these warnings, but they don't always cause real problems

**Comment by wambambizzle** [comment]
Yah, everything seems to work just fine. I prefer to handle any of the purple thread warnings that may cause hangs.

**Comment by nerzh** [comment]
yes, me too, but it pops up inside a library maintained by the apple server group. Yes, this seems like a warning, but I also trust Apple specialists enough, so I don’t pay attention to the QOS warning here specifically, various applications have been working with it for several years now

**Comment by wambambizzle** [comment]
That great to know, thank you for the response(s)!
