### ISSUE TITLE
How to read URLCredential?

### ISSUE THREAD

**Issue by lexuanquynh** [nerzh/Action-Cable-Swift#19]
Is there a way to read the URLCredential for this library?

**Comment by nerzh** [comment]
Hi, if for some reason this is not enough for you 
https://github.com/nerzh/Action-Cable-Swift?tab=readme-ov-file#authorization--headers
then no, the standard rails protocol did not accept other parameters during the development of this library

**Comment by lexuanquynh** [comment]
@nerzh 
We are using a bearer token for this socket in our application. However, due to business requirements, SSL must be installed.
I realize this is quite unreasonable as there are two layers of security, but this is a project requirement.

**Comment by lexuanquynh** [comment]
@nerzh 
Can you add an option to ignore SSL pin authentication?
I got this error when using Self-signature:
```
handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268435581 error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED 
```

**Comment by nerzh** [comment]
The fact is that I updated the readme file and wrote there that there is now a default web socket implementation. But I forgot to push the commits of this implementation and uploaded these changes right now. Based on this situation, I think that you used your provider, which was inherited from the websocket protocol, since you do not have these changes yet. So it is necessary to solve this problem in your implementation of the websocket protocol?

**Comment by lexuanquynh** [comment]
@nerzh
 thank for your response.
I tried using another library, Starscream.
When I installed it, it connected fine.
````
  let pinner = FoundationSecurity(allowSelfSigned: true)
         socket = WebSocket(request: request, certPinner: pinner)
````

So I am wondering if it is possible to omit SSL in the source code.
I am really a beginner so setting up Socket is a bit difficult for me.

**Comment by nerzh** [comment]
Starscream is fucking shit )
sorry but that's how it is 🙂

I added configurator for default socket implementation, try it maybe it will help you
<img width="550" alt="Снимок экрана 2024-01-18 в 08 52 43" src="https://github.com/nerzh/Action-Cable-Swift/assets/10519803/05617f0c-1dc4-499c-b69e-9d69b3982d23">

**Comment by lexuanquynh** [comment]
@nerzh  thank bro. I will try again.

**Comment by lexuanquynh** [comment]
@nerzh 
You saved my life.
I was really stuck in my code for 2 days.
Now I think I will share a little for someone in my case.
```Swift
 // Add ignore check SSL
        var tLSConfiguration = TLSConfiguration.makeClientConfiguration()
        tLSConfiguration.certificateVerification = .none
        let configuration: WebSocketClient.Configuration = .init(tlsConfiguration: tLSConfiguration)

        wss = .init(stringURL: socketURL, configuration: configuration)
```

It's going really well. Thank you so much.

**Comment by nerzh** [comment]
@lexuanquynh thanx, you welcome )
