### ISSUE TITLE
Could you add the license for this repository?

### ISSUE THREAD

**Issue by lexuanquynh** [nerzh/Action-Cable-Swift#20]
warning when I run the pod:

<img width="717" alt="Screenshot 2024-11-12 at 06 55 53" src="https://github.com/user-attachments/assets/593434bd-33ea-43f4-b314-ce6bd5263473">

**Comment by nerzh** [comment]
for 0.3.2 version ?

**Comment by nerzh** [comment]
oh, its cocoapods... right now cocoapods does not support

**Comment by lexuanquynh** [comment]
@nerzh 
Why you not support for Pod?

Why don't you support Pod?
I can't download Swift packages from Github, so I decided to use Pod.
More error when using the Swift package:

<img width="890" alt="Screenshot 2024-11-25 at 12 37 36" src="https://github.com/user-attachments/assets/76d5c531-d078-4a46-9b87-4b15e0c25a26">
