### ISSUE TITLE
Connection issue in actioncable

### ISSUE THREAD

**Issue by bacancy-jigar** [nerzh/Action-Cable-Swift#3]
Hello
i will try to connect websocket server but does not call any method in your code.can you please check your code

**Comment by nerzh** [comment]
Hello, you use starscream or websocket-kit for websocket client ?

**Comment by bacancy-jigar** [comment]
i am using starscream.if you want any code please tell me i will send

**Comment by bacancy-jigar** [comment]
please check my code
override func viewDidLoad() {
        super.viewDidLoad()
        let ws = WSS(stringURL: "ws://54.241.193.25/cable")
        
        /// action cable client
        let client = ACClient(ws: ws)
        //let options = ACChannelOptions(buffering: true, autoSubscribe: true)
        let channel = client.makeChannel(name: "TripChannel")
        try? channel.subscribe()
        channel.addOnSubscribe { (channel, optionalMessage) in
            print(optionalMessage)
        }
        channel.addOnMessage { (channel, optionalMessage) in
            print(optionalMessage)
        }
        channel.addOnPing { (channel, optionalMessage) in
            print("ping")
        }
        // Connect
        client.connect()
        // Do any additional setup after loading the view.
    }

in this code does not call any delegate method

**Comment by nerzh** [comment]
Try autoSubscribe: false
```swift
var options = ACChannelOptions(buffering: true, autoSubscribe: false)
```
and manual subscribe
```swift
client.addOnConnected { (headers) in
    try? channel.subscribe()
}
```


But best choose would be to use websocket-kit, because websocket-kit developed cool apple serverside team and it works perfect
https://github.com/nerzh/Action-Cable-Swift#use-with-websocket-kit

**Comment by bacancy-jigar** [comment]
i will try both code but could not connect sever wait i will share my code can you please check this
Here is my code = https://wetransfer.com/downloads/8fc1b2a16ed05c6edc0fd91eea68e50720200827091313/9313eeb1a73072b7e068ac21ecadaecd20200827091313/fdf980

**Comment by ahbou** [comment]
I'm having the same issue @bacancy-jigar  using WebSocket-Kit.

I'm able ton ping and connect to the WebSocket but I can't subscribe to my Channel using options.

The error server side is: **Couldn't handle non-string message: Array**

BTW subscribe with params doesn't exist in the code currently `try? channel.subscribe(params: ["Key": "Value"])`

**Comment by nerzh** [comment]
@ahbou yes, I forgot, in rails parameters can only be passed to the channel initializer as identifier dictionary =/
**The error server side is: Couldn't handle non-string message: Array**
which rails version are you using? maybe in new versions something changed in the actioncable protocol ... ?

**Comment by ahbou** [comment]
@nerzh Thanks for the quick reply. 
I've tried both 5.2 and 6.0.3.

Rails expects this payload: 
`{"command":"subscribe","identifier":"{\"channel\":\"ConversationChannel\",\"conversation_slug\":\"support-jimmy-sully\"}"}
`

Here's my code for creating the channel:

```
 let conversationIdentifier = ["conversation_slug": slug]
 let options = ACChannelOptions(buffering: true, autoSubscribe: true)
 let channel = client.makeChannel(name: "ConversationChannel", identifier: conversationIdentifier, options: options)
```

**Comment by nerzh** [comment]
@ahbou 
**{"command":"subscribe","identifier":"{\"channel\":\"ConversationChannel\",\"conversation_slug\":\"support-jimmy-sully\"}"}**

your web socket address are open or local test server ? I want try to connect and debug this case

**Comment by nerzh** [comment]
@bacancy-jigar  @ahbou I fixed case with **Couldn't handle non-string message: Array** please try release 0.3.2.
And make sure that the client and channel objects is declared "globally" and lives while your socket connection is needed

**Comment by nerzh** [comment]
@usmantariqdatainvent 
Answer to #2. 
I use this with https://github.com/anycable/anycable-go. And it can accept binary data but rails action cable were expecting only a string, so I added a flag in the function for sending messages to the websocket server, which by default sends a string
```swift
// channel.subscribe(sendAsData: Bool = false)

// default as string
try channel.subscribe()

// as data
try channel.subscribe(sendAsData: true)
```

**Comment by ahbou** [comment]
@nerzh Thank you! 
0.3.2 fixed the subscription issue. I'm able to subscribe and get messages but I can't send a message.

Upon debugging `sendMessage` in `ACChannel.swift` `isSubscribed` is false. So the send method is never called.

**EDIT** 

I fixed it by setting `autosubscribe = false` and adding the callbacks before calling `channel.subscribe()`

Great job on the lib very much needed 👍

**Comment by nerzh** [comment]
**autosubscribe = false**
I tested on Websocket-kit with this code
server
```ruby
class RoomChannel < ApplicationCable::Channel

  def subscribed
    p 'subscribed'
    stream_from 'stream_name'
  end

  def unsubscribed
    p 'unsubscribed'
  end

  def delete_room_message(data)
    p 'delete_room_message OK'
  end

  def speak(data)
    p 'SPEAK OK'
    ActionCable.server.broadcast('stream_name', {cool: 'job'})
  end
end
```

```swift
        let ws = WSS(stringURL: "ws://localhost:3001/cable")
        let clientOptions = ACClientOptions(debug: false, reconnect: true)
        let client = ACClient(ws: ws, options: clientOptions)
        client.headers = ["COOKIE": "Value"]
        let options = ACChannelOptions(buffering: true, autoSubscribe: true)
        let channel = client.makeChannel(name: "RoomChannel", identifier: [:], options: options)

        channel.addOnSubscribe { (channel, optionalMessage) in
            print("SUBSCRIBE")
            sleep(1)
            try? channel.sendMessage(actionName: "speak", data: ["test": 10101010101], {
                print("SENDED MESSAGE")
            })
            sleep(1)
            try? channel.sendMessage(actionName: "delete_room_message", data: ["test": 10101010101], {
                print("SENDED MESSAGE")
            })
        }
        channel.addOnMessage { (channel, optionalMessage) in
            print(optionalMessage)
        }
        channel.addOnPing { (channel, optionalMessage) in
            print("ping")
        }

       /// Connect
       client.connect()
```

And this works fine. But if you use starscream then autosubscribe = true and reconnect = true - really may not work, because starscream can get deadlock when reconnected

**Comment by nerzh** [comment]
@ahbou 

**Upon debugging sendMessage in ACChannel.swift isSubscribed is false. So the send method is never called.**
**autosubscribe = false**

I tested on Websocket-kit with this code
server
```ruby
class RoomChannel < ApplicationCable::Channel

  def subscribed
    p 'subscribed'
    stream_from 'stream_name'
  end

  def unsubscribed
    p 'unsubscribed'
  end

  def delete_room_message(data)
    p 'delete_room_message OK'
  end

  def speak(data)
    p 'SPEAK OK'
    ActionCable.server.broadcast('stream_name', {cool: 'job'})
  end
end
```

client

```swift
        let ws: WSS = .init(stringURL: "ws://localhost:3001/cable")
        let clientOptions: ACClientOptions = .init(debug: false, reconnect: true)
        let client: ACClient = .init(ws: ws, options: clientOptions)
        client.headers = ["COOKIE": "Value"]
        let channelOptions: ACChannelOptions = .init(buffering: true, autoSubscribe: true)
        let channel: ACChannel = client.makeChannel(name: "RoomChannel", identifier: ["test": "value"], options: channelOptions)

        channel.addOnSubscribe { (channel, optionalMessage) in
            print("SUBSCRIBE")
            sleep(1)
            try? channel.sendMessage(actionName: "speak", data: ["test": 10101010101], {
                print("SENDED speak MESSAGE")
            })
            sleep(1)
            try? channel.sendMessage(actionName: "delete_room_message", data: ["test": 10101010101], {
                print("SENDED delete_room_message MESSAGE")
            })
        }
        channel.addOnMessage { (channel, optionalMessage) in
            print(optionalMessage)
        }
        channel.addOnPing { (channel, optionalMessage) in
            print("ping")
        }

       /// Connect
       client.connect()
```

And this works fine. But if you use starscream then autosubscribe = true and reconnect = true - really may not work, because starscream can get deadlock when reconnected and maybe another problem ...

**Comment by ahbou** [comment]
I'll see if I can get autosubscribe to work.
But manually subscribing is something I can live with 👍

**Comment by nerzh** [comment]
> I'll see if I can get autosubscribe to work.
> But manually subscribing is something I can live with 👍

Ok, I will close this issue if you have any other questions please open again or make new issue, good luck :)
