### ISSUE TITLE
onPing / onPong never called?

### ISSUE THREAD

**Issue by wilg** [nerzh/Action-Cable-Swift#4]
As far as I can tell, `onPing` and `onPong` are never called – though I do see ping messages in `onText`

**Comment by nerzh** [comment]
Yes. Because the action cable rails does not send a message with type "ping". You ask me why? I do not know )

**Comment by nerzh** [comment]
Or why the identifier could be an object with a nested channel name or suddenly the string type "_ping"...
it all looks strange. I did it with some specification from the Internet, where ping was a separate type. Apparently this is not the case now. You can process the ping using onText. Maybe I'll fix it later

**Comment by wilg** [comment]
OK, no worries. Was trying to track down an issue and thought this might be the problem but it wasn't. Thanks for making this library!
