### ISSUE TITLE
The `send message` action is not working.

### ISSUE THREAD

**Issue by gevorgyanvahagn** [nerzh/Action-Cable-Swift#8]
here is an example of generated message which can't be parsed by server, 

`"{\"identifier\":\"{\\\"channel\\\":\\\"LivestreamChatsChannel\\\",\\\"livestream_id\\\":12}\",\"command\":\"message\",\"data\":\"{\\\"content\\\":\\\"hello!\\\",\\\"action\\\":\\\"chat\\\"}\"}"`

**Comment by gevorgyanvahagn** [comment]
the issue is I don't receive the message back

**Comment by nerzh** [comment]
my english is bad, maybe do you speak russian ?

**Comment by nerzh** [comment]
the point is that the error can be both on the server side and on the client side. Describe what exactly is your problem ?
it seems to me that you have a server side problem
